### ISSUE TITLE
Offset configuration

### ISSUE THREAD

**Issue by coord-e** [coord-e/servoarray.py#22]

**Comment by coord-e** [comment]
```toml
[offsets]
0 = 0.0
1 = 1.2
3 = ...
```
